blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list ,name = 'post_list'),
    url(r'^post/(?P<pk>\d+)/$' ,views.post_detail, name = 'post_detail'),
    url(r'^post/$', views.post_new , name = 'post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$' ,views.post_edit, name = 'post_edit'),

    url(r'^post/(?P<post_pk>\d+)/comment/$', views.comment_new, name ='comment_new'),
    url(r'^post/(?P<post_pk>\d+)/comment/(?P<pk>\d+)/edit/$',views.comment_edit, name='comment_edit'),

    url(r'^about/', views.about),
    url(r'^gallery/',views.gallery),

    url(r'^sum/(?P<x>\d+)/(?P<y>\d+)/(?P<z>\d+)/$',views.mysum),
    url(r'^sum/(?P<x>\d+)/(?P<y>\d+)/$',views.mysum),
    url(r'^sum/(?P<x>\d+)/$',views.mysum),
    url(r'^sum2/(?P<x>[\d/]+)/$', views.mysum2),

    url(r'^zipcode/$', views.zipcode, name = 'zipcode'),


    ]

programming/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from pokemon import views as pokemon_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', lambda request: redirect('/blog/')),
    # blog
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # login
    url(r'^accounts/', include('accounts.urls')),

    # pokemon
    url(r'^pokemon_main/$', pokemon_views.pokemon_main),
    url(r'^pokemon/$', pokemon_views.pokemon_list),
    url(r'^pokemon/(?P<pk>\d+)/$', pokemon_views.pokemon_detail),
    url(r'^player/$', pokemon_views.player_list),
    url(r'^player/(?P<pk>\d+)/$', pokemon_views.player_detail),
    url(r'^capture/$', pokemon_views.capture_list),
    url(r'^capture/(?P<pk>\d+)/$', pokemon_views.capture_detail),
    url(r'^place/$', pokemon_views.place_list),
    url(r'^place/(?P<pk>\d+)/$', pokemon_views.place_detail),


    # url(r'^zipcode_exist/$', views.zipcode_exist, name= 'zipcodecheck'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import os
from uuid import uuid4
from django.utils import timezone
from django.db import models
from django.forms import ValidationError
from django.utils import timezone
from .validators import *
from .customfield import *
from django.core.urlresolvers import reverse
from django.core.files import File
from django.db.models.signals import pre_save
from programming.pil_image import square_image, thumbnail


# def URL_validator(self):
#     val=URLValidator(verify_exists=True)
#     try:
#         val(self)
#     except:
#         raise ValidationError
# Create your models here.

def random_name_upload_to(instance, filename):
    name = uuid4().hex
    # 랜덤으로 16진수의 32자 숫자 생성.
    extension = os.path.splitext(filename)[-1].lower()
    # 확장자 구하는거 .로 스플릿해서 뒤에서 첫번쨰꺼
    return os.path.join(name[:3], name[3:6], name[6:] + extension)


class Post(models.Model):
    title = models.CharField(max_length=100,  validators = [MaxLengthValidator(100)] ,verbose_name ="제목")
    content = models.TextField(help_text="Markdown 문법을 써주세요.", validators = [MinLengthValidator(4)])
    tags = models.ManyToManyField('Tag', blank = True)
    lnglat = models.CharField(max_length=50,validators=[lnglat_validator], help_text="경도,위도 포맷으로 입력")
    created_at = models.DateTimeField(default=timezone.now)
    test_field = models.IntegerField(default=10 )
    image = models.ImageField(upload_to=random_name_upload_to, blank = True)


    def __str__(self):
        return "post: " + self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

    @property
    def lat(self):
        return self.lnglat.split(',')[1]

    @property   #변수인것처럼 쓰이면 함수가 호출되게하는것.
    def lng(self):
        return self.lnglat.split(',')[0]
def pre_on_post_save(sender, **kwargs):
    post = kwargs['instance']
    if post.image:

        # post.image = 이미지 저장경로
        # post.image.name = 이미지 파일명 확장자 포
        # post.image.path = 이미지 저장 절대경로
        # post.image.url = 이미지 URL
        # post.image.file = 지정 경로에 대한 파일 오브젝트,
        # post.image.width,height = 이미지 필드만됨.
        max_width = 300
        if post.image.width > max_width or post.image.height > max_width:
            processed_file = thumbnail(post.image.file, max_width, max_width)
            # processed_file = square_image(함post.image.file, max_width)
            post.image.save(post.image.name, File(processed_file))
pre_save.connect(pre_on_post_save, sender=Post)


class Comment(models.Model):
    post = models.ForeignKey(Post)
    message = models.TextField()
    author = models.CharField(max_length=20)
    Jall = models.ImageField(blank = True)

class Contact(models.Model):
    name = models.CharField(max_length = 20)
    phone_number = PhoneNumberField()

class Tag(models.Model):
    category = models.CharField(max_length=100, verbose_name = "태그")
    def __str__(self):
        return "tag: "+self.category
# -------------------------------------------------------------------
# class Calculator(object):
#     def __init__(self, base):
#         self.base = base

#     def __call__(self, x, y):



class ZipCode(models.Model):
    zipcode = models.CharField(max_length = 7, validators = [ZipCodeValidator], verbose_name = "우편번호")
    state = models.CharField(max_length = 20 , verbose_name = "시/도" , blank = True)
    city = models.CharField(max_length = 20 , verbose_name = "시/군/" , blank = True)
    roadname = models.CharField(max_length = 10, verbose_name = "도로명" , blank = True)
    def __str__(self):
        return "(우편번호 : "+self.zipcode+") (시/도 : " +self.state+ ") (시/군/구 : "+ self.city +") (도로명 : "+ self.roadname+")"



class Zip_Code(models.Model):
    zip_code = models.CharField(max_length =7)
    road = models.CharField(max_length =20)
    dong = models.CharField(max_length =20)
    gu = models.CharField(max_length =20)
    city = models.CharField(max_length =20)

blog/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from registration.forms import RegistrationForm
from django.core import validators
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.forms.widgets import TextInput
from .models import ZipCode, Comment, Post
from django import forms
import re


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content','tags', 'lnglat', 'image']

class ZipCodeForm(forms.ModelForm):
    class Meta:
        model = ZipCode
        fields = ['zipcode',]


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message', 'author', 'Jall']

blog/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from .models import ZipCode, Post, Comment, Tag
from blog.forms import *
from programming.pil_image import thumbnail, square_image
from django.core.files import File
from django.db.models.signals import pre_save

# message 예제
# messages.add-message(request, messages.INFO, "Hello world")
# ->숏컷 쓰면, messages.info(request, "Hello world")



def post_list(request):
    qs = Post.objects.all()
    context = {
        'post_list': qs,
    }
    return render(request, 'blog/post_list.html', context)

def post_detail(request, pk):
    # try:
    #     qs = Post.objects.get(pk=pk)
    # except Post.DoesNotExist:
    #     raise Http404
    # 위 네줄을 아래 한줄로 바꾸기
    qs = get_object_or_404(Post, pk=pk)
    qs_comment = Comment.objects.filter(post_id=pk)
    # 코멘트 불러올떄 post.comment_set.all로 불러와도된다 이게 더 편한듯?
    qs_tags = Tag.objects.filter(post__pk=pk)
    context = {
        'post': qs,
        'comment_list': qs_comment,
        'tags': qs_tags,

    }
    return render(request, 'blog/post_detail.html', context)

def post_new(request):

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid:
            form.save()
            return redirect('../')
    else:
        form = PostForm
    return render(request, 'blog/post_form.html', {'form':form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES ,instance=post)
        if form.is_valid:
            form.save()
            return redirect('/')
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {'form': form, })

def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == "POST":
        form = CommentModelForm(request.POST, request.FILES )
        if form.is_valid():
            comment = form.save(commit=False)
            # 바로 윗글을 디비에는 바로 저장하지 말라는것. 왜냐하면 post값을 지정을 안해줬음.
            # 그래서 아래에 지정을 해주는 것이다.
            comment.post = get_object_or_404(Post, pk=post_pk)
            form.save()
            messages.success(request,'새 댓글이 등록되었습니다.')  #-> 이거하고 html가서 템플릿태그등
            # return redirect('blog:post_detail', post_pk)
            return redirect(post)
            # 일단 겟 앱솔루트 url이 있는 확인하고 호출.
    else:
        form = CommentModelForm()
    return render(request, 'blog/comments_form.html', {'form': form, })

def comment_edit(request, post_pk, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if request.method == "POST":
        form = CommentModelForm(request.POST, request.FILES, instance = comment )
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = get_object_or_404(Post, pk = post_pk)
            form.save()
            return redirect('blog:post_detail', post_pk)
    else:
        form = CommentModelForm(instance = comment)
    return render(request, 'blog/comments_form.html', {'form' :form} )


def about(request):
    return render(request, 'blog/about.html', {})


def gallery(request):
    return render(request, 'blog/gallery.html', {})


def mysum(request, x, y=0, z=0):
    return HttpResponse(int(x) + int(y) + int(z))


def mysum2(request, x):
    result = sum(int(i) for i in x.split("/"))
    return HttpResponse(result)

def zipcode(request):
    title = "우편번호 검색"
    form = ZipCodeForm(request.POST or None)
    context = {'form': ZipCodeForm, "title" : title}

    if form.is_valid():
        zipcode = form.cleaned_data.get("zipcode")
        if ZipCode.objects.filter(zipcode = zipcode).exists():
            return render(request, 'blog/zipcode_exist.html', {"AreaList": ZipCode.objects.filter(zipcode =zipcode),})
        else:
            return HttpResponseRedirect(".zipcode_error/")
# context = {"title":"유효한 우편번호입니다."}
    return render(request, 'blog/zipcode.html', context)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block main %}

<style>
body{

    background-image:url('http://kmug.co.kr/board/data/illust/1288706667/smoon_BG005.gif');
    background-size:cover;
}
</style>

</head>
<body>
<style>
  .centeredauto { display: table; margin-left: auto; margin-right: auto; }
</style>

<div class="centeredauto">
  <div class="item">

<p>
<h1 align="center">권진환의 홈페이지에 오신것을 환영합니다!</h1>
    <h2 align="center"> 진환은 누구인가</h2>
<image src="https://scontent.xx.fbcdn.net/v/t1.0-9/12234902_927312040676643_2302218104281763969_n.jpg?oh=3e1349e0f466fe46a82a82a96a5c90fe&oe=57EE22B4" style="max-width:70 %; height: auto; margin-left:50% margin-right:50%; " alt="진환사진" title="진환사진" ><br><br>
<a href="https://search.naver.com/search.naver?where=nexearch&query=%EA%B6%8C%EC%A7%84%ED%99%98&sm=top_hty&fbm=1&ie=utf8" target="_blank" title="권진환 네이버검색결과">권진환 네이버 검색결과</a>
</p>

<ol>
    <p><li><h3>자기소개</h3></li>
    이름은 권진환, 성별 남자 ,1991년생. 컴퓨터 만지는걸 좋아하는 이상한 취미. <br>
    소프트웨어에 입문해보고자 피로그래밍 지원.<br>
    사는곳은 서울 홍대. 그런데 문제는 이사와서 놀 사람이 없음.<br>
    2015년 2학기는 독일로 교환학생을 다녀왔음.<br>
    사실 베를린공대썼는데 학점때문에 밀려서 아헨공대감<br>
    좋아하는 가수는 없음. 근데 여자친구 시간을 달려서 노래는 좀 좋은듯.</p>


    <p><li><h3>취미</h3></li>
     현재까지 알려진 취미는 다음과 같음
        <ul>
            <li>사진찍기</li>
            <li>요리하기</li>
            <li>마술하기</li>
            <li>잠자기, 밥먹기, X싸기</li>
            <li>핫딜 카톡방 운영중</li>
        </ul><br>
       아래는 유럽여행가서 찍은 사진. 페이스북에 올려놓은게 이것밖에..<br><br>
    <image src="/static/about/pics/pic1.jpg" height="200">,<image src="/static/about/pics/pic2.jpg" height="200"><br><br>
    아까 위에서 여자친구 시간을 달려서 좋아한다고 했는데..<br>
    동영상도..ㅎㅎㅎ.ㅎ.ㅎ.ㅎ.ㅎ.ㅎ.ㅎ<br>
    이런건 크게봐야 제맛.<br><br>
 <video width="600" controls="autoplay">

        <source src="/static/about/videos/girlfriends.mp4">
    </video><br><br>


    <li>특징</li>
        있는데 집에가느라 못씀..

</ol>

 </div>
</div>

{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<title>P.rogramming Blog</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<style>

body {
    padding-top: 60px;
}
html {
  position: relative;
  min-height: 100%;
}
body {
  margin-bottom: 60px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 60px;
  background-color: #f5f5f5;
}
.navbar-right {
  position : relative;
  align-self: right;
  color:red;
}
.alert-debug{
  background-color: #eeeeee;
  border-color: #eeeeee;
  color: #333;
/* 해당 디버그는 기본 부트스트랩에 없음*/
}
</style>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/#/">P.rogramming Django</a>
            <div class="navbar-right">
              <a class="navbar-brand" href="/blog/aboutme" >About.Me</a>
              <a class='navbar-brand' href="/pokemon_main">Pokemon</a>
              <a class="navbar-brand" href="/blog/gallery/">Gallery.Me</a>
              <a class="navbar-brand" href="/blog/zipcode/">ZipCode</a>

            </div>
        </div>
    </div>
</div>

{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }} </li>
    {% endfor %} </ul>
{% endif %}

{% block main %}
{% endblock %}



<div class="footer">
    <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
    </div>
</div>

</body>
</html>

blog/templates/blog/comments_form.html
<form action="." method ="post" enctype ="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<input type = "submit">
</form>

blog/templates/blog/form.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="ko"  xml:lang="ko">
<meta http-equiv="Content-Type" Content="text/html; charset=utf-8" />
<html>
<head>
    <title>sign up form</title>
<style>
body{

    background-image:url('pics/pic4.jpg');
    background-size:cover;
}
</style>

<h2 align="center"> 회원가입을 하시려면, 아래의 빈칸을 채워주시기 바랍니다.</h2>
</head>
<body>

<form action="서버주소..." method="post" align="center">
<table border="2" align="center">
    <tr>
        <td><label for="id_txt">아이디</label></td>

        <td><input id="id_txt" type="text" name="id" required placeholder="아이디를 입력해주세요(필수)" size="52px"></td>
    </tr>
    <tr>
        <td><label for="password">비밀번호</label></td>
        <td><input id="password" type="password" name="pwd" required placeholder="비밀번호는 8자 이상(필수)" pattern="........+" size="52px"></td>
    </tr>
    <tr>
        <td><label for="address">주소</label></td>
        <td><input type="text" name="address" placeholder="주소를 입력해 주세요(선택)" size="52px"></td>
    </tr>
    <tr>
        <td><label for="phone number"> 전화번호</label></td>
        <td><input type="text" name="phone number" required placeholder="전화번호를 입력해 주세요(필수)" size="52px"></td>
    </tr>
    <tr>
        <td><label for="email">이메일 </label></td>
        <td><input type="email" name="email" placeholder="이메일 입력" required size="52px"></td>
    </tr>
    <tr>
        <td>자기소개:</td>
        <td><textarea cols="50" rows="5"></textarea></td>
    </tr>
    </table>


    <input type="submit" name="회원정보 전송" value="회원가입 신청">
</form>
</body>
</html>

blog/templates/blog/gallery.html
{% extends 'blog/base.html' %}

{% block main %}
	<meta charset="utf-8">
	<head>
		<link rel="stylesheet" type="text/css" href="/static/gallery/style.css" >
		<script src="/static/gallery/script.js"></script>
	</head>
	<body>
	<h1> these are Jin's pictures</h1>
	<hr>
	<input type="button" value ="Select All" onclick ="selectAll(this)">
	<input type="button" value ="Play Slideshow" onclick ="slideshow(this)">
	<hr>
	</body>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block main %}

<div class="container">
    <div class="jumbotron">
        <h1>P.rogramming</h1>
        <p>Hi. this is Jin's blog.</p>
    </div>
</div>
{% if post.image %}
<div class ='col-sm-6 col-sm-offset-3'>
    <img src="{{post.image.url}}" class = 'img-responsive' >
</div>
{% endif %}
<hr>
<table>
<tr>
    <td>글 제목 :{{post.title}}</td>
</tr>
    <td>글 내용 :{{post.content}}</td>
</tr>
    <td>작성 위치 :<img src="https://maps.googleapis.com/maps/api/staticmap?center={{ post.lat }},{{ post.lng }}&size=100x100&zoom=5&maptype=roadmap&markers=color:blue%7Clabel:S%7C{{ post.lat }},{{ post.lng }}" /></td>
</tr>
    <td>작성 시각 :{{post.created_at}}</td>
</tr>
    <td>    <h4>태그목록</h4>
<br>{% for tag in tags %} {{tag.category}} {% endfor %}

    </td>
</table>
<div>
<h4>댓글목록</h4>
<table>
{% for comment in comment_list %}
{# 코멘트 불러올떄 post.comment_set.all로 불러와도된다 이게 더 편한듯? #}
<tr>
{% if comment.Jall %}
 <img src ="{{comment.Jall.url}}" style ="width:50px; height:50px">
{% endif %}
        {{comment.message}} by {{comment.author}}<a class="btn btn-default" href='{% url "blog:comment_edit" post.pk comment.pk %}' role="button">댓글수정</a>
</tr>
{% empty %}
        <tr>첫번째 댓글의 주인공이 되어주세요.</tr>
{% endfor %}
</table>
<a href="{% url 'blog:comment_new' post.pk %}">댓글쓰기</a>
</table>
<hr>
<a class="btn btn-default" role="button" href="{% url 'blog:post_edit'  post.pk %}">글 수정</a>
<a class="btn btn-default" role="button" href="{% url 'blog:post_list' %}">목록으로</a>


{% endblock %}

blog/templates/blog/post_form.html
<form action="." method ="post" enctype ="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<input type = "submit">
</form>

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block main %}

<div class="container">
    <div class="jumbotron">
        <h1>P.rogramming</h1>
        <p>Hi. this is Jin's blog</p>
    </div>
</div>

<h2> 블로그 글 목록입니다..</h2>
<table>
{% for post in post_list %}
<tr>
{% if post.image %}
    <td>
    <div class ="thumbnail">
    <img src="{{post.image.url}}" class = 'img-responsive' style="width:75px; height:75px;">
    </td>
    </div>
{% endif %}
</div>
    <td><a href="{% url 'blog:post_detail' post.pk %}"> {{ post.title }} </a></td>
</tr>
{% endfor %}
</table>

<br>
<a class='btn btn-default' role = "button" href="{% url 'blog:post_new' %}">새글쓰기</a>




<div class="footer">
    <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
    </div>
</div>

</body>
</html>

{% endblock %}

blog/templates/blog/zipcode.html
{% extends 'blog/base.html' %}
{% block main %}

{{title}}

<form method ="POST" action ="">{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='submit'>

</form>

{% endblock %}

blog/templates/blog/zipcode_exist.html
{% extends 'blog/base.html' %}
{% block main %}
<h1> 해당 우편번호의 주소들은 다음과 같습니다..</h1>


<table>
{% for area in AreaList %}
<tr>
<td>
     {{area.zipcode}} {{area.state}}{{area.city}}{{area.roadname}}
</td>
</tr>
{% endfor %}
</table>



{% endblock %}